**TITANIC DATASET**

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/Titanic-Dataset.csv",encoding='latin1')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
df.shape

(891, 12)

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
df[df['Sex']=='female']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [ ]:
df[df['Age']>30]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df[df['Pclass']==1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [ ]:
df[(df['Sex']=='female')&(df['Pclass']==1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [ ]:
df['Age'].mean()

np.float64(29.69911764705882)

In [ ]:
df['Fare'].max()

512.3292

In [ ]:
df['Fare'].min()

0.0

In [ ]:
df['Survived'].sum()

np.int64(342)

NUMPY

In [ ]:
import numpy as np

In [ ]:
a=np.arange(1,26)
b=a.reshape(5,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

In [ ]:
print(b[0])

[1 2 3 4 5]

In [ ]:
print(b[:,-1])

[ 5 10 15 20 25]

In [ ]:
print(b[2,2])

13

In [ ]:
print(b[:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

In [ ]:
c=b**2
print(c)

[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]
 [256 289 324 361 400]
 [441 484 529 576 625]]

In [ ]:
print(np.sqrt(b))

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]
 [3.31662479 3.46410162 3.60555128 3.74165739 3.87298335]
 [4.         4.12310563 4.24264069 4.35889894 4.47213595]
 [4.58257569 4.69041576 4.79583152 4.89897949 5.        ]]

In [ ]:
print(b.sum())

325

In [ ]:
p=np.random.rand(10,100)
print(p)

[[0.49032374 0.27173371 0.39897352 0.94706384 0.44159896 0.89464701
  0.69387284 0.17545235 0.32327148 0.50994434 0.84147994 0.31403466
  0.02646186 0.55918006 0.35911312 0.74939049 0.31826851 0.88999237
  0.28503    0.26263009 0.95437634 0.31343919 0.97306577 0.4428067
  0.94436561 0.99234378 0.50464727 0.35019732 0.21313018 0.0165145
  0.68407245 0.55974258 0.56717703 0.00545714 0.08547235 0.74202658
  0.56103488 0.52253812 0.4854397  0.78732205 0.68897193 0.45036866
  0.4092087  0.92770817 0.39982385 0.32947969 0.57125116 0.44824748
  0.98548067 0.18379146 0.79653609 0.59031632 0.04417984 0.22013828
  0.27644297 0.63032572 0.87750707 0.64225696 0.38215552 0.47589348
  0.1706237  0.443552   0.3669962  0.33589598 0.35568775 0.47033625
  0.14481855 0.25608243 0.11760574 0.49234622 0.82401401 0.21732339
  0.71072887 0.13110178 0.30125435 0.93759256 0.02795234 0.40580739
  0.62237044 0.10749536 0.05548458 0.87291744 0.01171126 0.94307888
  0.8204903  0.26990294 0.55516065 0.39114338 0.84321156 0.29197952
  0.82929646 0.85379621 0.19130608 0.54531062 0.14254833 0.28202332
  0.63022332 0.72993905 0.94608231 0.43685934]
 [0.78439079 0.03657581 0.70362656 0.33101054 0.15953386 0.6913131
  0.68532094 0.74553276 0.45666986 0.09836442 0.61535406 0.49172166
  0.12560375 0.6238442  0.63598762 0.93898925 0.46249947 0.64166689
  0.87158048 0.04285907 0.82181675 0.51486391 0.42929163 0.4089353
  0.90475218 0.46850018 0.31328507 0.32170836 0.2107269  0.46839555
  0.45752307 0.45146326 0.23728378 0.87100594 0.53786866 0.25409739
  0.8104268  0.81295188 0.44551075 0.49867962 0.68041255 0.10478758
  0.94039885 0.67046234 0.82570961 0.25950014 0.50645984 0.09637219
  0.02406864 0.60272227 0.30336263 0.12165667 0.28367083 0.3012631
  0.65730124 0.07528632 0.20530257 0.82275099 0.21031749 0.90280503
  0.3239043  0.48885744 0.84770905 0.74235117 0.03072028 0.09751712
  0.4603973  0.08697341 0.65241094 0.18869225 0.68713925 0.45616714
  0.29742764 0.02473753 0.1361431  0.40269011 0.48726796 0.74696998
  0.33840336 0.84571375 0.8258719  0.82825238 0.56428742 0.72980946
  0.62965156 0.64749045 0.0174859  0.92120513 0.48411137 0.16311652
  0.46074852 0.14163277 0.6556908  0.43335562 0.18083621 0.69696649
  0.09968676 0.2375396  0.62668506 0.55973085]
 [0.76714862 0.21675124 0.08625925 0.45590543 0.15479115 0.07679222
  0.06628503 0.17007777 0.39764562 0.554359   0.22333844 0.8977076
  0.15130842 0.47935813 0.7269703  0.20088181 0.79116871 0.88457814
  0.07346741 0.86608718 0.1413858  0.06320822 0.72975151 0.8888694
  0.04016719 0.21060106 0.43954532 0.69564782 0.01304884 0.73616648
  0.88152008 0.83273539 0.53552102 0.53064789 0.32593982 0.25722198
  0.20837731 0.46966265 0.97222206 0.87648998 0.12509102 0.4431745
  0.64700196 0.48176619 0.44203402 0.51857471 0.76065501 0.64680019
  0.76191252 0.88565299 0.25342221 0.9305723  0.80410653 0.92826632
  0.75837958 0.26493957 0.49220538 0.19021562 0.00615021 0.77491158
  0.45170833 0.36088972 0.48966039 0.77413589 0.02575405 0.32076578
  0.89139789 0.58478812 0.22989521 0.98374792 0.14010275 0.66725284
  0.68246149 0.66134881 0.77302212 0.30265151 0.89959699 0.03574222
  0.37579236 0.67459644 0.55161236 0.75331907 0.06232535 0.58391858
  0.46603096 0.46127361 0.05405408 0.62029058 0.7474434  0.48889211
  0.72058857 0.62423746 0.77442305 0.07332868 0.97355972 0.66129007
  0.71359126 0.93436579 0.76277877 0.27496244]
 [0.88930005 0.11023132 0.62265561 0.10017305 0.61883394 0.14194266
  0.12385491 0.41852047 0.30955168 0.58190154 0.90807419 0.39057635
  0.44180792 0.63610904 0.2453275  0.94425653 0.23958655 0.56394483
  0.76397685 0.12906575 0.13785732 0.61707626 0.60423872 0.78269028
  0.83388597 0.7487954  0.08849849 0.04677482 0.94370781 0.03330008
  0.10291089 0.78888642 0.04234037 0.93182621 0.61557615 0.03474453
  0.65649357 0.70172989 0.62676544 0.01398729 0.27712327 0.94765235
  0.98644391 0.79861776 0.97134726 0.3109542  0.13374875 0.5525509
  0.24948617 0.92049962 0.18574671 0.11250133 0.91166668 0.21935905
  0.40943137 0.34839596 0.57523203 0.75447093 0.52987902 0.32678621
  0.65019008 0.33637788 0.46570389 0.0421574  0.61186346 0.81768952
  0.83300408 0.23742963 0.35132481 0.13749393 0.70502647 0.45239784
  0.10629814 0.29517318 0.35892425 0.7322987  0.25955802 0.98755486
  0.42390442 0.13209631 0.51536148 0.38654833 0.74500414 0.32127461
  0.8111596  0.31823341 0.94893223 0.38964514 0.93210448 0.98318174
  0.5339347  0.80511084 0.90439044 0.0539328  0.47176428 0.31668726
  0.43332085 0.91514314 0.72403267 0.65571644]
 [0.28162853 0.11062967 0.9382197  0.16984347 0.67817011 0.72967125
  0.25406494 0.16906946 0.04877845 0.75785307 0.95542289 0.64754769
  0.63181607 0.32732809 0.02779141 0.29394724 0.72437061 0.86566778
  0.52282972 0.63572548 0.15279019 0.85220788 0.19593417 0.01114333
  0.80970775 0.24825178 0.63501582 0.55280624 0.71296908 0.00683553
  0.73328592 0.88183845 0.09881204 0.42484981 0.34308204 0.74538998
  0.08663768 0.43440092 0.53637468 0.13920514 0.56110243 0.56891321
  0.81631985 0.23448046 0.15910394 0.24461222 0.44858185 0.35403254
  0.32825686 0.40754452 0.98405299 0.17949335 0.27049375 0.73554765
  0.09597532 0.48420207 0.16172129 0.38480639 0.17524629 0.63442483
  0.03781239 0.02873619 0.45113962 0.66545006 0.98261373 0.52217937
  0.07212298 0.31981459 0.24746726 0.35967671 0.46864254 0.65130982
  0.53548766 0.33789256 0.35426197 0.68250426 0.81499072 0.37826579
  0.1059399  0.23763891 0.21521795 0.83997388 0.31781964 0.92969071
  0.79435037 0.53478712 0.36567255 0.06589237 0.50952291 0.32220635
  0.3741151  0.01007992 0.92880426 0.33854864 0.95939946 0.33657335
  0.76789739 0.76774704 0.05683648 0.10074121]
 [0.07430283 0.87909897 0.58165049 0.79465296 0.46141476 0.47306548
  0.12089714 0.27244743 0.0158022  0.80256542 0.09825508 0.14601371
  0.58600121 0.94446605 0.81338857 0.9290603  0.51603431 0.58760921
  0.07044244 0.0755113  0.41236217 0.00941926 0.06671983 0.30159692
  0.8620787  0.50513996 0.75091154 0.1946974  0.99271587 0.28711381
  0.04354701 0.54408717 0.08484795 0.91616878 0.03211424 0.55597195
  0.54665347 0.87043743 0.64678678 0.3530901  0.86456389 0.60021732
  0.34153056 0.78605677 0.38643814 0.19621082 0.24992742 0.68075569
  0.63125321 0.75492345 0.40579481 0.19331641 0.58234762 0.52549347
  0.87420163 0.51249709 0.78506466 0.77270902 0.93673331 0.73712673
  0.1765808  0.13429227 0.80870274 0.93927783 0.92441525 0.52466168
  0.60961872 0.03506925 0.28473772 0.87461064 0.1016645  0.76522972
  0.00214962 0.48070465 0.41004198 0.0117999  0.0635217  0.49142929
  0.96085858 0.66386197 0.13989277 0.16861954 0.65231243 0.95950225
  0.23669817 0.99916987 0.93985536 0.59140515 0.39615945 0.00258511
  0.47807479 0.67717751 0.74717123 0.0042698  0.14706114 0.78725865
  0.99780826 0.64859296 0.86810809 0.4874267 ]
 [0.86774375 0.37982239 0.86752227 0.07254049 0.65523834 0.85442617
  0.83506982 0.88347001 0.33285179 0.3702918  0.13022369 0.0343634
  0.09858817 0.90362087 0.9590092  0.78909487 0.35391368 0.09554963
  0.13294131 0.85442371 0.22902574 0.22205082 0.06139362 0.67125036
  0.03478193 0.33425544 0.87004698 0.95924881 0.50470237 0.07893283
  0.33429138 0.96439649 0.2817941  0.33753472 0.9612417  0.44735169
  0.45953886 0.61691507 0.28336509 0.77571765 0.20210504 0.01053227
  0.78005437 0.02432218 0.42022972 0.75200286 0.02690769 0.29196041
  0.00201645 0.39650147 0.20390899 0.04622444 0.6385359  0.13689811
  0.87791397 0.115206   0.86936436 0.99112882 0.88021314 0.79647754
  0.5327304  0.46686277 0.32039251 0.62031647 0.15649323 0.46351646
  0.13899495 0.50120176 0.57395933 0.05829345 0.77597157 0.54893477
  0.42292029 0.87160637 0.91799444 0.14652829 0.50621101 0.20539443
  0.88844146 0.55697186 0.27003912 0.32173153 0.01104936 0.59516232
  0.65317348 0.93967464 0.92312948 0.21280363 0.53803786 0.59715929
  0.72899724 0.08241491 0.19088617 0.70539086 0.91922548 0.37938406
  0.72119323 0.89936525 0.20076852 0.64226648]
 [0.50473601 0.91841357 0.09196221 0.72747622 0.93988497 0.34939625
  0.6386108  0.18265001 0.17478107 0.28134822 0.11946789 0.96097095
  0.83096783 0.15578999 0.28231919 0.77247798 0.70359794 0.53687228
  0.89978122 0.88731532 0.62544153 0.32276981 0.07403036 0.11337933
  0.78347073 0.19298861 0.12529311 0.25029505 0.96511169 0.80615737
  0.98962393 0.19447809 0.94112009 0.5713858  0.23387295 0.57598596
  0.03350616 0.11748379 0.70848388 0.00821465 0.61003678 0.31164151
  0.83176437 0.06628988 0.05794377 0.73213808 0.80496155 0.34379454
  0.3845959  0.92203127 0.17566638 0.42345835 0.48968946 0.4705482
  0.51625179 0.58903993 0.33438183 0.1503232  0.40071213 0.37125408
  0.59730379 0.67288845 0.47872334 0.94910978 0.5545373  0.83799733
  0.8872936  0.40158167 0.23251772 0.38285087 0.1393323  0.83997345
  0.59319554 0.08939303 0.63268626 0.38371693 0.55544032 0.99130487
  0.5912046  0.06412058 0.05352606 0.39749657 0.68391844 0.65657632
  0.7109857  0.39624284 0.76153084 0.52449226 0.33887519 0.7294209
  0.92838121 0.16404877 0.93239898 0.81246864 0.94465846 0.57593803
  0.50030478 0.75300715 0.02530374 0.33575524]
 [0.7391373  0.00364506 0.20557395 0.93208503 0.28322751 0.23541921
  0.08624048 0.35034895 0.41498229 0.74619705 0.19569051 0.45406243
  0.02640832 0.23679121 0.75568489 0.70403007 0.04055988 0.64369437
  0.68615007 0.96759454 0.17711763 0.46858012 0.2315044  0.21910634
  0.15315814 0.02153391 0.22788613 0.28687475 0.55575321 0.39357022
  0.18154611 0.10576285 0.52686285 0.62928567 0.79258052 0.31699008
  0.71486687 0.84194964 0.24397561 0.80401974 0.91090509 0.34409914
  0.28138904 0.91863656 0.26856601 0.65515746 0.92444859 0.87731934
  0.90065843 0.06876614 0.392938   0.75660466 0.97691611 0.60212202
  0.33684468 0.71707707 0.3831499  0.9840714  0.95901085 0.68497503
  0.4718189  0.13489505 0.56110573 0.86449979 0.75056095 0.46683826
  0.45760033 0.18598454 0.94410438 0.48977783 0.47635666 0.43641412
  0.85414289 0.97830248 0.70243058 0.85832519 0.0140684  0.94577809
  0.44839987 0.22843796 0.99472081 0.64972946 0.49984514 0.24443612
  0.77111553 0.0162468  0.25431655 0.22239366 0.91530333 0.98787931
  0.85856867 0.55406202 0.27185391 0.09238233 0.08193501 0.60219238
  0.55938318 0.47839516 0.07119302 0.01280969]
 [0.93378454 0.9872559  0.82792369 0.17199259 0.26547727 0.31285836
  0.62813722 0.75927455 0.22251708 0.78110636 0.08222809 0.31908205
  0.39598705 0.44899808 0.73650345 0.18245064 0.78564132 0.3767305
  0.94994913 0.28905898 0.30206595 0.49801507 0.83037217 0.69302526
  0.14340909 0.24005218 0.54289994 0.29541598 0.95435596 0.89033216
  0.08738772 0.01462224 0.56606637 0.04385573 0.19836814 0.11774717
  0.12046308 0.35859863 0.92006092 0.98034165 0.26386904 0.85402487
  0.16769687 0.54342428 0.55320839 0.37355271 0.73662639 0.91660023
  0.19963997 0.81633648 0.47085122 0.8088103  0.19452196 0.60846109
  0.66849439 0.2104282  0.01572998 0.64028877 0.93301991 0.54561694
  0.33291285 0.15121788 0.73352036 0.22946056 0.14933309 0.09099449
  0.34878926 0.10436091 0.10889068 0.43656745 0.10757444 0.57254492
  0.3771087  0.8516194  0.04889355 0.20069618 0.16291636 0.9499679
  0.89877987 0.64857456 0.18685625 0.60621649 0.57275435 0.69066028
  0.09688825 0.84241439 0.10219445 0.31686144 0.20743992 0.76316853
  0.69159104 0.00298451 0.83544668 0.80776642 0.9480886  0.26593152
  0.16541408 0.2244772  0.79736753 0.59011656]]

In [ ]:
p.max()

np.float64(0.999169871800536)

In [ ]:
p.min()

np.float64(0.0020164458095405235)

In [ ]:
p.std()

np.float64(0.2948495313990039)

In [ ]:
age_array = df['Age'].to_numpy()
print(type(age_array))
print(age_array)

<class 'numpy.ndarray'>
[22.   38.   26.   35.   35.     nan 54.    2.   27.   14.    4.   58.
 20.   39.   14.   55.    2.     nan 31.     nan 35.   34.   15.   28.
  8.   38.     nan 19.     nan   nan 40.     nan   nan 66.   28.   42.
   nan 21.   18.   14.   40.   27.     nan  3.   19.     nan   nan   nan
   nan 18.    7.   21.   49.   29.   65.     nan 21.   28.5   5.   11.
 22.   38.   45.    4.     nan   nan 29.   19.   17.   26.   32.   16.
 21.   26.   32.   25.     nan   nan  0.83 30.   22.   29.     nan 28.
 17.   33.   16.     nan 23.   24.   29.   20.   46.   26.   59.     nan
 71.   23.   34.   34.   28.     nan 21.   33.   37.   28.   21.     nan
 38.     nan 47.   14.5  22.   20.   17.   21.   70.5  29.   24.    2.
 21.     nan 32.5  32.5  54.   12.     nan 24.     nan 45.   33.   20.
 47.   29.   25.   23.   19.   37.   16.   24.     nan 22.   24.   19.
 18.   19.   27.    9.   36.5  42.   51.   22.   55.5  40.5    nan 51.
 16.   30.     nan   nan 44.   40.   26.   17.    1.    9.     nan 45.
   nan 28.   61.    4.    1.   21.   56.   18.     nan 50.   30.   36.
   nan   nan  9.    1.    4.     nan   nan 45.   40.   36.   32.   19.
 19.    3.   44.   58.     nan 42.     nan 24.   28.     nan 34.   45.5
 18.    2.   32.   26.   16.   40.   24.   35.   22.   30.     nan 31.
 27.   42.   32.   30.   16.   27.   51.     nan 38.   22.   19.   20.5
 18.     nan 35.   29.   59.    5.   24.     nan 44.    8.   19.   33.
   nan   nan 29.   22.   30.   44.   25.   24.   37.   54.     nan 29.
 62.   30.   41.   29.     nan 30.   35.   50.     nan  3.   52.   40.
   nan 36.   16.   25.   58.   35.     nan 25.   41.   37.     nan 63.
 45.     nan  7.   35.   65.   28.   16.   19.     nan 33.   30.   22.
 42.   22.   26.   19.   36.   24.   24.     nan 23.5   2.     nan 50.
   nan   nan 19.     nan   nan  0.92   nan 17.   30.   30.   24.   18.
 26.   28.   43.   26.   24.   54.   31.   40.   22.   27.   30.   22.
   nan 36.   61.   36.   31.   16.     nan 45.5  38.   16.     nan   nan
 29.   41.   45.   45.    2.   24.   28.   25.   36.   24.   40.     nan
  3.   42.   23.     nan 15.   25.     nan 28.   22.   38.     nan   nan
 40.   29.   45.   35.     nan 30.   60.     nan   nan 24.   25.   18.
 19.   22.    3.     nan 22.   27.   20.   19.   42.    1.   32.   35.
   nan 18.    1.   36.     nan 17.   36.   21.   28.   23.   24.   22.
 31.   46.   23.   28.   39.   26.   21.   28.   20.   34.   51.    3.
 21.     nan   nan   nan 33.     nan 44.     nan 34.   18.   30.   10.
   nan 21.   29.   28.   18.     nan 28.   19.     nan 32.   28.     nan
 42.   17.   50.   14.   21.   24.   64.   31.   45.   20.   25.   28.
   nan  4.   13.   34.    5.   52.   36.     nan 30.   49.     nan 29.
 65.     nan 50.     nan 48.   34.   47.   48.     nan 38.     nan 56.
   nan  0.75   nan 38.   33.   23.   22.     nan 34.   29.   22.    2.
  9.     nan 50.   63.   25.     nan 35.   58.   30.    9.     nan 21.
 55.   71.   21.     nan 54.     nan 25.   24.   17.   21.     nan 37.
 16.   18.   33.     nan 28.   26.   29.     nan 36.   54.   24.   47.
 34.     nan 36.   32.   30.   22.     nan 44.     nan 40.5  50.     nan
 39.   23.    2.     nan 17.     nan 30.    7.   45.   30.     nan 22.
 36.    9.   11.   32.   50.   64.   19.     nan 33.    8.   17.   27.
   nan 22.   22.   62.   48.     nan 39.   36.     nan 40.   28.     nan
   nan 24.   19.   29.     nan 32.   62.   53.   36.     nan 16.   19.
 34.   39.     nan 32.   25.   39.   54.   36.     nan 18.   47.   60.
 22.     nan 35.   52.   47.     nan 37.   36.     nan 49.     nan 49.
 24.     nan   nan 44.   35.   36.   30.   27.   22.   40.   39.     nan
   nan   nan 35.   24.   34.   26.    4.   26.   27.   42.   20.   21.
 21.   61.   57.   21.   26.     nan 80.   51.   32.     nan  9.   28.
 32.   31.   41.     nan 20.   24.    2.     nan  0.75 48.   19.   56.
   nan 23.     nan 18.   21.     nan 18.   24.     nan 32.   23.   58.
 50.   40.   47.   36.   20.   32.   25.     nan 43.     nan 40.   31.
 70.   31.     nan 18.   24.5  18.   43.   36.     nan 27.   20.   14.
 60.   25.   14.   19.   18.   15.   31.    4.     nan 25.   60.   52.
 44.     nan 49.   42.   18.   35.   18.   25.   26.   39.   45.   42.
 22.     nan 24.     nan 48.   29.   52.   19.   38.   27.     nan 33.
  6.   17.   34.   50.   27.   20.   30.     nan 25.   25.   29.   11.
   nan 23.   23.   28.5  48.   35.     nan   nan   nan 36.   21.   24.
 31.   70.   16.   30.   19.   31.    4.    6.   33.   23.   48.    0.67
 28.   18.   34.   33.     nan 41.   20.   36.   16.   51.     nan 30.5
   nan 32.   24.   48.   57.     nan 54.   18.     nan  5.     nan 43.
 13.   17.   29.     nan 25.   25.   18.    8.    1.   46.     nan 16.
   nan   nan 25.   39.   49.   31.   30.   30.   34.   31.   11.    0.42
 27.   31.   39.   18.   39.   33.   26.   39.   35.    6.   30.5    nan
 23.   31.   43.   10.   52.   27.   38.   27.    2.     nan   nan  1.
   nan 62.   15.    0.83   nan 23.   18.   39.   21.     nan 32.     nan
 20.   16.   30.   34.5  17.   42.     nan 35.   28.     nan  4.   74.
  9.   16.   44.   18.   45.   51.   24.     nan 41.   21.   48.     nan
 24.   42.   27.   31.     nan  4.   26.   47.   33.   47.   28.   15.
 20.   19.     nan 56.   25.   33.   22.   28.   25.   39.   27.   19.
   nan 26.   32.  ]

In [ ]:
age_array.mean()

np.float64(nan)

In [ ]:
np.median(age_array)

np.float64(nan)

In [ ]:
np.std(age_array)

np.float64(nan)

In [ ]:
np.var(age_array)

np.float64(nan)